%YAML 1.1
---
# Suricata configuration file
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
  port-groups:
    HTTP_PORTS: "80"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: 1521
    SSH_PORTS: 22

default-rule-path: /etc/suricata/rules
rule-files:
  - custom.rules

classification-file: /etc/suricata/rules/reference.config
reference-config-file: /etc/suricata/rules/reference.config

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes
  - eve-log:
      enabled: yes
      type: file
      filename: eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - ssh
        - smtp
        - flow
        - netflow
      filetype: regular
      rotate-interval: 24h
      metadata: yes

logging:
  default-log-level: info
  outputs:
    - console:
        enabled: no
    - file:
        enabled: yes
        filename: /var/log/suricata/suricata.log
        append: yes
        level: info
